# Generated by Django 6.0.6 on 2026-06-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_file_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedFile',
        ),
        migrations.DeleteModel(
            name='SharedFolder',
        ),
    ]
